[package]
name = "relay"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
face_id = { version = "0.4.1", features = ["cuda"] }
image = "0.25.10"
imageproc = "0.27.0"
ort = "2.0.0-rc.12"
shared = { path = "../shared", features = ["std"] }
tokio = { version = "1.52.3", features = ["full", "net", "rt"] }
